/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerateReportRouteImport } from './routes/generate_.report'
import { Route as GeneratePptRouteImport } from './routes/generate_.ppt'

const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateReportRoute = GenerateReportRouteImport.update({
  id: '/generate_/report',
  path: '/generate/report',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratePptRoute = GeneratePptRouteImport.update({
  id: '/generate_/ppt',
  path: '/generate/ppt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/generate': typeof GenerateRoute
  '/generate/ppt': typeof GeneratePptRoute
  '/generate/report': typeof GenerateReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/generate': typeof GenerateRoute
  '/generate/ppt': typeof GeneratePptRoute
  '/generate/report': typeof GenerateReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/generate': typeof GenerateRoute
  '/generate_/ppt': typeof GeneratePptRoute
  '/generate_/report': typeof GenerateReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/generate' | '/generate/ppt' | '/generate/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/generate' | '/generate/ppt' | '/generate/report'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/generate'
    | '/generate_/ppt'
    | '/generate_/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GenerateRoute: typeof GenerateRoute
  GeneratePptRoute: typeof GeneratePptRoute
  GenerateReportRoute: typeof GenerateReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate_/report': {
      id: '/generate_/report'
      path: '/generate/report'
      fullPath: '/generate/report'
      preLoaderRoute: typeof GenerateReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate_/ppt': {
      id: '/generate_/ppt'
      path: '/generate/ppt'
      fullPath: '/generate/ppt'
      preLoaderRoute: typeof GeneratePptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GenerateRoute: GenerateRoute,
  GeneratePptRoute: GeneratePptRoute,
  GenerateReportRoute: GenerateReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
